version = "3.1"

[services.mongo]
image = "mongo"
restart = "always"
ports = [ "27017:27017" ]

  [services.mongo.environment]
  MONGO_INITDB_ROOT_USERNAME = "root"
  MONGO_INITDB_ROOT_PASSWORD = "pa55word"

[services.mongo-express]
image = "mongo-express"
restart = "always"
ports = [ "8081:8081" ]
depends_on = [ "mongo" ]

  [services.mongo-express.environment]
  ME_CONFIG_MONGODB_ADMINUSERNAME = "root"
  ME_CONFIG_MONGODB_ADMINPASSWORD = "pa55word"

[services.register-credentials-server]
restart = "always"
ports = [ "7184:80" ]
depends_on = [ "mongo" ]

  [services.register-credentials-server.build]
  context = "."
  dockerfile = "Dockerfile"

  [services.register-credentials-server.environment]
  MongoDB__Host = "mongo"
